K: 10
center_init_clipping_bound: 21
center_init_contributed_components_clipping_bound: 10
center_init_epsilon_split: 0.5
center_init_gaussian_epsilon: 0.25
clustering_algorithm: FederatedLloyds
datapoint_privacy: false
dataset: GaussianMixtureUniform
dim: 100
fedlloyds_clipping_bound: 120
fedlloyds_epsilon: 0.25
fedlloyds_laplace_clipping_bound: 50
fedlloyds_num_iterations: 1
initialization_algorithm: FederatedClusterInitExact
minimum_server_point_weight: 5
num_train_clients: 100
num_uniform_server: 100
outer_product_clipping_bound: 1500
outer_product_epsilon: 0.25
samples_per_client: 1000
samples_per_mixture_server: 20
weighting_clipping_bound: 1
weighting_epsilon: 0.25
